name: Install CI deps

inputs:
  cache-key:
    required: false
  local-cache:
    required: false
  GITHUB_TOKEN:
    required: true
    description: "GITHUB_TOKEN needed to make GitHub API requests"

runs:
  using: "composite"

  steps:
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v8
      with:
        github-token: ${{ inputs.GITHUB_TOKEN }}
        # Do not use systemd
        init: none

    - name: Set up Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@v3

    - name: Install CI deps
      shell: bash
      run: |
        # Remove previously installed nix profiles
        nix profile remove '.*'
        # Install the current one
        nix profile install .#ci-deps
        # Set up CI environment
        nix run .#ci-env >> $GITHUB_ENV

    - id: get-info
      name: Get info
      shell: bash
      run: |
        RUST_VERSION="$(taplo get -f rust-toolchain.toml 'toolchain.channel')"
        echo "cache-primary-key=toolchain-${{ runner.os }}-${{ runner.arch }}-${RUST_VERSION}" >> "$GITHUB_OUTPUT"

    - id: toolchain-cache-restore
      name: Restore Cargo Cache (Local Restore)
      if: ${{ inputs.local-cache }}
      uses: 0xmozak/local-cache/restore@ff33c7264117faa1bbd99aa0ddb467a9ccc3919e
      with:
        key: ${{ steps.get-info.outputs.cache-primary-key }}
        path: |
          ~/.cargo/git
          ~/.cargo/registry

    - id: toolchain-cache-save
      name: Persist Cargo Cache (Local Save)
      if: ${{ steps.toolchain-cache-restore.outputs.cache-hit != 'true' }}
      uses: 0xmozak/local-cache/save@ff33c7264117faa1bbd99aa0ddb467a9ccc3919e
      with:
        key: ${{ steps.get-info.outputs.cache-primary-key }}
        path: |
          ~/.cargo/git
          ~/.cargo/registry

    - id: local-cache
      name: Cache Rust artifacts (Local)
      uses: 0xmozak/rust-cache@d5f76b3ac4ba287ab299d4d3586d5cd11ad21cab
      with:
        prefix-key: ${{ inputs.cache-key != '' && inputs.cache-key || null }}
        cache-provider: "local"

    - name: Debug
      shell: bash
      run: echo cache-hit=${{ steps.local-cache.outputs.cache-hit }} partial-hit=${{ steps.local-cache.outputs.partial-hit }}

    - name: Cache Rust artifacts (Remote)
      uses: 0xmozak/rust-cache@d5f76b3ac4ba287ab299d4d3586d5cd11ad21cab
      if: ${{ steps.local-cache.outputs.cache-hit != 'true'}}
      with:
        require-full-match: ${{ steps.local-cache.outputs.partial-hit }}
        prefix-key: ${{ inputs.cache-key != '' && inputs.cache-key || null }}
