[package]
edition = "2021"
name = "poseidon2-example-mozak-guest"
version = "0.1.0"

[dependencies]
guest = { path = "../../guest", default-features=false }
hex-literal = "0.2"

[[bin]]
name = "poseidon2-example"
path = "main.rs"

[features]
std = ["guest/std"]
