[package]
edition = "2021"
name = "poseidon2-example-mozak-guest"
version = "0.1.0"

[dependencies]
hex-literal = "0.2"
mozak-sdk = { path = "../../sdk", default-features = false }

[target.'cfg(not(target_os="mozakvm"))'.dependencies.mozak-sdk]
path = "../../sdk"

[[bin]]
name = "poseidon2-example"
path = "main.rs"

[features]
std = ["mozak-sdk/std"]
