#!/opt/homebrew/bin/bash
# MOZAK_STARK_DEBUG=true \
# RUST_BACKTRACE=1 \
# time nice \
# cargo nextest run \


MOZAK_STARK_DEBUG=true \
RUST_BACKTRACE=1 \
cargo test --package mozak-circuits --lib -- bitshift::stark::tests::prove_sll --exact --nocapture 
  # --nocapture \


  # cpu::branches::tests::prove_branch_proptest


  # cpu::mul::tests::prove_mulh_proptest
