[workspace]
[package]
edition = "2021"
name = "mozak-sort-mozakvm"
version = "0.1.0"

[dependencies]
mozak-sdk = { path = "../../../sdk", default-features = false }
rand = { version = "0.8", default_features = false, features = ["alloc", "small_rng"] }
