[package]
edition = "2021"
name = "stdin-mozak-guest"
version = "0.1.0"

[dependencies]
guest = { path = "../../guest", default-features = false}

mozak-system = { path = "../../system"}

[features]
std = ["guest/std"]

[[bin]]
name = "stdin"
path = "main.rs"
