[package]
edition = "2021"
name = "stdin-mozak-guest"
version = "0.1.0"

[target.'cfg(target_os="zkvm")'.dependencies.guest]
path = "../../guest"

[features]
x86 = []

[[bin]]
name = "stdin"
path = "main.rs"

[[bin]]
name = "stdin-x86"
path = "main_x86.rs"
required-features = ["x86"]
