[package]
edition = "2021"
name = "stdin-mozak-guest"
version = "0.1.0"

[target.'cfg(target_os="zkvm")'.dependencies.guest]
path = "../../guest"

[features]
native = []

[[bin]]
name = "stdin"
path = "main.rs"

[[bin]]
name = "stdin-native"
path = "main_native.rs"
required-features = ["native"]
