[package]
edition = "2021"
name = "mozak-rpc"
version = "0.1.0"

categories = ["cryptography", "rpc"]
description = "Mozak protocol rpc"
keywords = ["crypto", "zero-knowledge", "rpc"]
license = "All rights reserved"
readme = "README.md"
repository = "https://github.com/0xmozak/mozak-node"
