[package]
edition = "2021"
name = "min-max-mozak-guest"
version = "0.1.0"

[dependencies]
mozak-sdk = { path = "../../sdk", default-features = false }

[features]
std = ["mozak-sdk/std"]

[[bin]]
name = "min-max"
path = "main.rs"
