[package]
edition = "2021"
name = "min-max-mozak-guest"
version = "0.1.0"

[dependencies]
guest = { path = "../../guest", default-features = false }

[features]
std = ["guest/std"]

[[bin]]
name = "min-max"
path = "main.rs"
