[package]
edition = "2021"
name = "merkleproof-trustedroot-mozak-guest"
version = "0.1.0"

[target.'cfg(target_os="zkvm")'.dependencies.guest]
features = ["std"]
path = "../../guest"

[target.'cfg(target_os="zkvm")'.dependencies.mozak_sdk]
path = "../../sdk"

[features]
native = []

[dependencies]
rs_merkle = { version = "1.4", default-features = false }
rkyv = { version = "0.7", default-features = false, features = ["size_32", "alloc"] }

[[bin]]
name = "merkleproof-trustedroot"
path = "main_mozak.rs"

[[bin]]
name = "merkleproof-trustedroot-native"
path = "main_native.rs"
required-features = ["native"]
