version: "3"
name: mozak
services:
  runner:
    # image: myoung34/github-runner:latest
    # image: nginx:latest
    build: .
    deploy:
      replicas: $MOZAK_RUNNER_REPLICAS
    # Ensure nix daemon is working before starting build agents
    depends_on:
      nix:
        condition: service_healthy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${MOZAK_RUNNER_CACHE}:/opt/hostedtoolcache"
      - "nix-store:/nix"
      
    environment:
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      RUNNER_NAME_PREFIX: ${RUNNER_NAME_PREFIX}
      RUNNER_GROUP: default
      RUNNER_SCOPE: org
      ORG_NAME: 0xmozak
      RUNNER_WORKDIR: /tmp/github-runner-mozak
      LABELS: ubuntu-latest
    labels:
      net.unraid.docker.icon: "https://pbs.twimg.com/profile_images/1708417671694340096/RO2UoJdM_400x400.jpg"
  nix:
    build: .
    volumes:
      - "nix-store:/nix"
    entrypoint: ["/root/.nix-profile/bin/nix", "daemon"]
    # Check if we can build a small nix package from a know version of nixpkgs
    healthcheck:
      test: nix build --no-link github:NixOS/nixpkgs/nixos-23.11-small#hello || exit 1
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 0s
    labels:
      net.unraid.docker.icon: "https://pbs.twimg.com/profile_images/663784290925289472/ET9J1uY-_400x400.png"

volumes:
  nix-store:
