# Keeping this for legacy purposes - the commands below in `alias` are based off this configuration.
# [unstable]
# build-std = ["alloc", "core", "compiler_builtins", "std", "panic_abort", "proc_macro"]
# build-std-features = ["compiler-builtins-mem"]

# [build]
# rustflags = ["-C", "passes=loweratomic", "-Zlocation-detail=none"]
# target = "./.cargo/riscv32im-mozak-mozakvm-elf.json"

[alias]
mozakvm-build = """
    build --profile mozak-release \
          --target riscv32im-mozak-mozakvm-elf \
          -Zbuild-std=alloc,core,compiler_builtins,std,panic_abort,proc_macro \
          -Zbuild-std-features=compiler-builtins-mem
    """
mozakvm-check = """
    check \
        --target riscv32im-mozak-mozakvm-elf \
        -Zbuild-std=alloc,core,compiler_builtins,std,panic_abort,proc_macro \
        -Zbuild-std-features=compiler-builtins-mem \
    """
mozakvm-clippy = """
    clippy \
        --target riscv32im-mozak-mozakvm-elf \
        -Zbuild-std=alloc,core,compiler_builtins,std,panic_abort,proc_macro \
        -Zbuild-std-features=compiler-builtins-mem \
    """
mozakvm-run = """
    run --profile mozak-release \
          --target riscv32im-mozak-mozakvm-elf \
          -Zbuild-std=alloc,core,compiler_builtins,std,panic_abort,proc_macro \
          -Zbuild-std-features=compiler-builtins-mem 
    """
[target.riscv32im-mozak-mozakvm-elf]
runner = "examples/scripts/run_script.sh"
rustflags = ["-C", "passes=loweratomic", "-Zlocation-detail=none"]

[env]
# path where riscv32im-mozak-mozakvm-elf.json lies
RUST_TARGET_PATH = { value = ".cargo/", relative = true, force = true }

[profile.mozak-dev]
inherits = "dev"
panic = "abort"

# profile for mozakvm binaries
[profile.mozak-release]
codegen-units = 1
inherits = "release"
lto = "fat"
opt-level = 3
panic = "abort"
strip = true
