[package]
edition = "2021"
name = "static-mem-access"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
guest = { path = "../../guest" }

[[bin]]
name = "static-mem-access"
path = "main.rs"
