[package]
edition = "2021"
name = "inputtape-native"
version = "0.1.0"

[dependencies]
inputtape-core-logic = { path = "../core-logic" }
inputtape-elf-data = { path = "../elf-data" }
mozak-sdk = { path = "../../../sdk" }
