[package]
edition = "2021"
name = "memory-access"
version = "0.1"

[dependencies]
mozak-sdk = { path = "../../sdk", default-features = false }

[[bin]]
name = "memory-access"
path = "main.rs"

[features]
std = ["mozak-sdk/std"]
