[package]
edition = "2021"
name = "memory-access-mozak-guest"
version = "0.1.0"

[dependencies]
guest = { path = "../../guest", default-features = false }

[[bin]]
name = "memory-access"
path = "main.rs"

[features]
std = ["guest/std"]
