[package]
edition = "2021"
name = "wallet-core-logic"
version = "0.1.0"

[dependencies]
mozak-sdk = { path = "../../../sdk" }
rkyv = { version = "=0.8.0-alpha.1", default-features = false, features = ["pointer_width_32", "alloc"] }
rkyv_derive = "=0.8.0-alpha.1"

[target.'cfg(not(target_os="mozakvm"))'.dependencies]
hex = "0.4"
rand = "0.8"
rand_chacha = "0.3"
