[workspace]

[package]
edition = "2021"
name = "guest"
version = "0.1.0"

[dependencies]
mozak-system = { path = "../system" }

[target.'cfg(not(target_os="zkvm"))'.dependencies.plonky2]
git = "https://github.com/0xmozak/plonky2.git"
default-features = false

[features]
std = ["plonky2/std"]
