name: Install rust toolchain

inputs:
  cache-key:
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - id: rust-version
      name: Get rust version
      shell: bash
      run: echo "RUST_VERSION=$(cat rust-toolchain.toml| grep '^channel\s*=' | cut -d '=' -f2 | sed 's/"//g' | sed -e 's/^[ \t]*//')" >> "$GITHUB_OUTPUT"

    - name: Install toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ steps.rust-version.outputs.RUST_VERSION }}
        components: rustfmt, clippy

    - name: Install nextest
      uses: taiki-e/install-action@nextest

    - uses: Swatinem/rust-cache@v2
      if: ${{ inputs.cache-key != '' }}
      with:
        prefix-key: ${{ inputs.cache-key }}

    - uses: Swatinem/rust-cache@v2
      if: ${{ inputs.cache-key == '' }}
