name: Install rust toolchain

inputs:
  cache-key:
    required: false
  local-cache:
    required: false

runs:
  using: "composite"
  steps:
    - id: get-info
      name: Get info
      shell: bash
      run: |
        RUST_VERSION="$(cat rust-toolchain.toml | grep '^channel\s*=' | cut -d '=' -f2 | sed 's/"//g' | sed -e 's/^[ \t]*//')"
        echo "rust-version=${RUST_VERSION}" >> "$GITHUB_OUTPUT"
        echo "cache-primary-key=toolchain-${{ runner.os }}-${{ runner.arch }}-${RUST_VERSION}" >> "$GITHUB_OUTPUT"

    - id: toolchain-cache-restore
      name: Cache Rust toolchain (Local Restore)
      if: ${{ inputs.local-cache }}
      uses: 0xmozak/local-cache/restore@ff33c7264117faa1bbd99aa0ddb467a9ccc3919e
      with:
        key: ${{ steps.get-info.outputs.cache-primary-key }}
        path: |
          ~/.rustup
          ~/.cargo

    - name: Restore Path
      if: ${{ steps.toolchain-cache-restore.outputs.cache-hit }}
      shell: bash
      run: echo "${HOME}/.cargo/bin" >> $GITHUB_PATH

    - name: Install toolchain
      if: ${{ steps.toolchain-cache-restore.outputs.cache-hit != 'true' }}
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ steps.get-info.outputs.rust-version }}
        components: rustfmt, clippy

    - name: Install nextest
      if: ${{ steps.toolchain-cache-restore.outputs.cache-hit != 'true' }}
      uses: taiki-e/install-action@nextest

    - name: Install taplo-cli
      shell: bash
      run: |
        cargo install --force --git https://github.com/tamasfe/taplo taplo-cli --no-default-features

    - id: toolchain-cache-save
      name: Cache Rust toolchain (Local Save)
      if: ${{ steps.toolchain-cache-restore.outputs.cache-hit != 'true' }}
      uses: 0xmozak/local-cache/save@ff33c7264117faa1bbd99aa0ddb467a9ccc3919e
      with:
        key: ${{ steps.get-info.outputs.cache-primary-key }}
        path: |
          ~/.rustup
          ~/.cargo

    - id: local-cache
      name: Cache Rust artifacts (Local)
      uses: 0xmozak/rust-cache@d5f76b3ac4ba287ab299d4d3586d5cd11ad21cab
      with:
        prefix-key: ${{ inputs.cache-key != '' && inputs.cache-key || null }}
        cache-provider: "local"

    - name: Debug
      shell: bash
      run: echo cache-hit=${{ steps.local-cache.outputs.cache-hit }} partial-hit=${{ steps.local-cache.outputs.partial-hit }}

    - name: Cache Rust artifacts (Remote)
      uses: 0xmozak/rust-cache@d5f76b3ac4ba287ab299d4d3586d5cd11ad21cab
      if: ${{ steps.local-cache.outputs.cache-hit != 'true'}}
      with:
        require-full-match: ${{ steps.local-cache.outputs.partial-hit }}
        prefix-key: ${{ inputs.cache-key != '' && inputs.cache-key || null }}
