name: Install rust toolchain

inputs:
  cache-key:
    required: false

runs:
  using: "composite"
  steps:
    - id: rust-version
      name: Get rust version
      run: echo "RUST_VERSION=$(cat rust-toolchain.toml| grep '^channel\s*=' | cut -d '=' -f2 | sed 's/"//g' | sed -e 's/^[ \t]*//')" >> "$GITHUB_OUTPUT"
      shell: bash

    - id: cache-rustup-restore
      name: Cache Rust toolchain (Restore)
      uses: actions/cache/restore@v3
      with:
        path: |
          ~/.rustup
          ~/.cargo
        key: toolchain-${{ runner.os }}-${{ runner.arch }}-${{ steps.rust-version.outputs.RUST_VERSION }}

    - name: Restore Path
      if: ${{ steps.cache-rustup-restore.outputs.cache-hit }}
      run: echo "~/.cargo/bin" >> $GITHUB_PATH
      shell: bash

    - name: Install toolchain
      if: ${{ steps.cache-rustup-restore.outputs.cache-hit != 'true' }}
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ steps.rust-version.outputs.RUST_VERSION }}
        components: rustfmt, clippy

    - name: Install nextest
      if: ${{ inputs.nextest }}
      uses: taiki-e/install-action@nextest

    - id: cache-rustup-save
      if: ${{ steps.cache-rustup-restore.outputs.cache-hit != 'true' }}
      name: Cache Rust toolchain (Save)
      uses: actions/cache/save@v3
      with:
        path: |
          ~/.rustup
          ~/.cargo
        key: ${{ steps.cache-rustup-restore.outputs.cache-primary-key }}

    - uses: Swatinem/rust-cache@v2
      if: ${{ inputs.cache-key != '' }}
      with:
        prefix-key: ${{ inputs.cache-key }}

    - uses: Swatinem/rust-cache@v2
      if: ${{ inputs.cache-key == '' }}
