[package]
edition = "2021"
name = "fibonacci"
version = "0.1"

[dependencies]
mozak-sdk = { path = "../../sdk", default-features = false }

[features]
std = ["mozak-sdk/std"]

[[bin]]
name = "fibonacci"
path = "main.rs"
