[package]
edition = "2021"
name = "bss-tester"
version = "0.1.0"

[dependencies]
mozak-sdk = { path = "../../sdk", default-features = false }

[features]
std = []

[[bin]]
name = "bss-tester"
path = "main.rs"
