[package]
name = "signatures"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.0"
mozak-circuits = { version = "0.1.0", path = "../circuits" }
plonky2 = "0.1"

[dev-dependencies]
env_logger = { version = "0.10" }
rand = "0.8.5"
