#!/bin/bash

# Description: This script will run given command for
# all mozakvm examples in examples directory. For
# example, to build all mozakvm examples, run
#
# `./scripts/all_mozakvm_examples cargo mozakvm-build`

set -euo pipefail

for example in *; do
    if [ -d "$example" ]; then
        cd "$example"
        for target in *; do
            if [ "$target" == "mozakvm" ]; then
                cd mozakvm
                "$@"
                cd ..
            fi
        done
        cd ..
    fi
done
