on:
  workflow_call:
    secrets:
      READ_RUNNERS_TOKEN:
        required: true
    outputs:
      runner-label:
        description: "The runner label to use"
        value: ${{ jobs.check-runner.outputs.runner-label }}

jobs:
  check-runner:
    runs-on: ubuntu-latest
    outputs:
      runner-label: ${{ steps.set-runner.outputs.runner-label }}

    steps:
      - name: Set runner
        id: set-runner
        run: |
          curl_runners () {
            local -r url="$1"
            runners=$(curl --silent --show-error \
              --header "Accept: application/vnd.github+json" \
              --header "Authorization: Bearer ${{ secrets.READ_RUNNERS_TOKEN }}" \
              --header "X-GitHub-Api-Version: 2022-11-28" \
              --location "${url}" || echo "")
            echo "${runners}"
            if echo "${runners}" | jq --exit-status '(.runners // [])[] | select(.status == "online" and (.busy == false or .name == "${{ runner.name }}") and .labels[] .name == "self-hosted")'; then
              echo "runner-label=self-hosted" | tee --append "${GITHUB_OUTPUT}"
              exit 0
            fi
          }

          curl_runners "https://api.github.com/repos/${{ github.repository }}/actions/runners"
          curl_runners "https://api.github.com/orgs/${{ github.repository_owner }}/actions/runners"

          echo "runner-label=ubuntu-latest" | tee --append "${GITHUB_OUTPUT}"
