on:
  workflow_call:
    secrets:
      READ_RUNNERS_TOKEN:
        required: true
    outputs:
      runner-label: ${{ steps.set-runner.outputs.runner-label }}
        description: "The runner label to use"
        value: ${{ jobs.check-runner.outputs.runner-label }}

jobs:
  check-runner:
    runs-on: ubuntu-latest
    outputs:
      runner-label: ${{ steps.set-runner.outputs.runner-label }}

    steps:
      - name: Set runner
        id: set-runner
        run: |
          runners=$(curl \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.READ_RUNNERS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -L https://api.github.com/repos/${{ github.repository }}/actions/runners || echo "")
          available=$(echo "$runners" | jq '(.runners // [])[] | select(.status == "online" and .busy == false and .labels[] .name == "self-hosted")')
          echo "$runners"
          if [ -n "$available" ]; then
            echo "available1"
            echo "runner-label=self-hosted" >> $GITHUB_OUTPUT
            exit 0
          fi

          runners=$(curl \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.READ_RUNNERS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -L https://api.github.com/orgs/${{ github.repository_owner }}/actions/runners || echo "")
          echo "$runners"
          available=$(echo "$runners" | jq '(.runners // [])[] | select(.status == "online" and .busy == false and .labels[] .name == "self-hosted")')
          if [ -n "$available" ]; then
            echo "runner-label=self-hosted" >> $GITHUB_OUTPUT
          else
            echo "runner-label=ubuntu-latest" >> $GITHUB_OUTPUT
          fi