name: coverage_hybrid

on:
  push:
    branches: [ "main" ]
  pull_request: {}

env:
  CARGO_TERM_COLOR: always
  NIGHTLY_RUST_VERSION: nightly-2023-05-17

jobs:
  coverage:
    runs-on: ubuntu-latest
    container:
      image:                    xd009642/tarpaulin:develop-nightly
      options:                  --security-opt seccomp=unconfined
    steps:
      - uses: actions/checkout@v3
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.NIGHTLY_RUST_VERSION }}

      - uses: Swatinem/rust-cache@v2

      - name: Try loading RISC-V tests from cache
        id: cache-built-tests
        uses: actions/cache@v3
        with:
          path: vm/tests/testdata
          key: "${{ runner.os }}-riscv-tests-${{ hashFiles('vm/tests/create_testdata/') }}"

      - name: Set up Docker Buildx
        if: ${{ steps.cache-built-tests.outputs.cache-hit != 'true' }}
        uses: docker/setup-buildx-action@v2

      - name: Run tests
        run: cargo tarpaulin --locked --workspace
