name:                           coverage

on:
    push:
      branches: [ "main" ]
    pull_request: {}

env:
    CARGO_TERM_COLOR: always
    NIGHTLY_RUST_VERSION: nightly-2023-05-17

jobs:
  test:
    name:                       coverage
    runs-on:                    ubuntu-latest
    container:
      image:                    xd009642/tarpaulin:develop-nightly
      options:                  --security-opt seccomp=unconfined
    steps:
      - uses: actions/checkout@v3
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.NIGHTLY_RUST_VERSION }}
      - uses: Swatinem/rust-cache@v2

      - name: Try loading RISC-V tests from cache
        id: cache-built-tests
        uses: actions/cache@v3
        with:
          path: vm/tests/testdata
          key: ${{ runner.os }}-riscv-tests-${{ github.ref_name }}
          restore-keys: ${{ runner.os }}-riscv-tests-${{ github.ref_name }}

      - name: Set up Docker Buildx
        if: ${{ steps.cache-built-tests.outputs.cache-hit != 'true' }}
        uses: docker/setup-buildx-action@v2

      - name:                   Generate testdata (via `cargo check`)
        run: |
          cargo check
        #   cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out Xml

      - name:                   Generate code coverage
        run: |
          cargo tarpaulin --locked --workspace
        #   cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out Xml

      - name: Populate RISC-V test cache
        if: ${{ steps.cache-built-tests.outputs.cache-hit != 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: riscv-tests
          path: vm/tests/testdata

    #   - name:                   Upload to codecov.io
    #     uses:                   codecov/codecov-action@v2
    #     with:
    #       # token:                ${{secrets.CODECOV_TOKEN}} # not required for public repos
    #       fail_ci_if_error:     true
