name: Check RISC-V Tests are up to date

on:
  push:
    branches:
      - release/*
    tags:
      - "*"

  # Triggers the workflow every sunday
  schedule:
    - cron: "0 18 * * 0"

env:
  CARGO_TERM_COLOR: always

jobs:
  check-runner:
    runs-on: ubuntu-latest
    outputs:
      runner-label: ${{ steps.set-runner.outputs.runner-label }}

    steps:
      - name: Set runner
        id: set-runner
        run: |
          available=$((curl \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.READ_RUNNERS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -sL https://api.github.com/repos/${{ github.repository }}/actions/runners || echo "") | \
          jq '(.runners // [])[] | select(.status == "online" and .busy == false and .labels[] .name == "self-hosted")')
          if [ -n "$available" ]; then
            echo "runner-label=self-hosted" >> $GITHUB_OUTPUT
            exit 0
          fi

          available=$((curl \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.READ_RUNNERS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -sL https://api.github.com/orgs/${{ github.repository_owner }}/actions/runners || echo "") | \
          jq '(.runners // [])[] | select(.status == "online" and .busy == false and .labels[] .name == "self-hosted")')
          if [ -n "$available" ]; then
            echo "runner-label=self-hosted" >> $GITHUB_OUTPUT
          else
            echo "runner-label=ubuntu-latest" >> $GITHUB_OUTPUT
          fi

  check-riscv-tests:
    name: "Check RISC-V Tests are up to date"
    needs: check-runner
    runs-on: ${{ needs.check-runner.outputs.runner-label }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Check if RISC-V tests are up to date
        run: |
          git ls-remote --quiet --heads https://github.com/riscv/riscv-tests.git master |
              grep --only '^[^[:space:]]*' |
              tee vm/tests/testdata/.testdata_generated_from_this_commit
          git diff --exit-code || {
              echo "::error RISCV tests are out of date";
              cat vm/tests/create_testdata/error_message.markdown >> ${GITHUB_STEP_SUMMARY};
              false
          }

      - name: Update RISC-V tests
        if: ${{ failure() }}
        id: update-risc-v-tests
        run: ./update_testdata

      - name: Create Pull Request using new test files
        id: create-pr
        if: ${{ failure() && steps.update-risc-v-tests.outcome == 'success' }}
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "update: RISC-V tests files"
          committer: Mozak Bot <bot@mozak.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: github/actions/update-riscv-tests
          delete-branch: true
          title: "Update RISC-V tests"
          add-paths: |
            vm/
          body: |
            This PR is automatically generated as part of Github actions.
            Here is the action job: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          labels: |
            risc-v tests
            automated pr

      - name: Check PR outputs
        if: ${{ failure() && steps.create-pr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.create-pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.create-pr.outputs.pull-request-url }}"
