name: Unused dependencies

on:
  # Triggers the workflow every sunday
  schedule:
    - cron: "0 18 * * 0"

env:
  CARGO_TERM_COLOR: always

jobs:
  check-runner:
    uses: ./.github/workflows/check-runner.yml
    secrets: inherit

  cargo-udeps:
    needs: check-runner
    runs-on: ${{ needs.check-runner.outputs.runner-label }}
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4
        # Main branch is default branch
        # with:
        #   ref: main

      - name: Install rust toolkit
        uses: ./.github/actions/rust

      - name: Install cargo-udeps
        run: cargo install --features vendored-openssl --locked cargo-udeps

      - name: Check for unused dependencies
        run: cargo udeps --workspace --all-targets --all-features

      - name: Create github issue for failed action
        uses: imjohnbo/issue-bot@v3
        if: ${{ failure() }}
        with:
          assignees: "jdkanani, matthiasgoergens"
          labels: "bug, devtools"
          title: "Github action for unused deps check failed"
          body: |
            Failed reference github action job: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            The reference ${{ github.ref_type }} ${{ github.ref }} was at commit ${{ github.sha }} when its run failed.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
