name: Unused dependencies

on:
  # Triggers the workflow every sunday
  schedule:
    - cron: "0 18 * * 0"

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-udeps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # Main branch is default branch
        # with:
        #   ref: main

      - name: Install rust toolkit
        uses: ./.github/actions/rust

      - name: Install cargo-udeps
        run: cargo install --locked cargo-udeps

      - name: Check for unused dependencies
        run: cargo udeps --workspace --all-targets --all-features
