name: Unused dependencies

on:
  # Triggers the workflow every sunday
  schedule:
    - cron: "0 18 * * 0"

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-udeps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4
        # Main branch is default branch
        # with:
        #   ref: main
      - name: Install CI deps
        uses: ./.github/actions/ci-deps
        with:
          runner-label: ubuntu-latest
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for unused dependencies
        run: nixdo nice cargo udeps --workspace --all-targets --all-features

      - name: Create github issue for failed action
        uses: imjohnbo/issue-bot@v3
        if: ${{ failure() }}
        with:
          assignees: "jdkanani, matthiasgoergens"
          labels: "bug, devtools"
          title: "Github action for unused deps check failed"
          body: |
            Failed reference github action job: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            The reference ${{ github.ref_type }} ${{ github.ref }} was at commit ${{ github.sha }} when its run failed.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
