name: Unused dependencies

on:
  # Triggers the workflow every sunday
  schedule:
    - cron: "0 18 * * 0"

env:
  CARGO_TERM_COLOR: always

jobs:
  check-runner:
    runs-on: ubuntu-latest
    outputs:
      runner-label: ${{ steps.set-runner.outputs.runner-label }}

    steps:
      - name: Set runner
        id: set-runner
        run: |
          runners=$((curl \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.READ_RUNNERS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -sL https://api.github.com/repos/${{ github.repository }}/actions/runners || echo "") | \
          jq '(.runners // [])[] | select(.status == "online" and .busy == false and .labels[] .name == "self-hosted")'
          if [ -n "$available" ]; then
            echo "runner-label=self-hosted" >> $GITHUB_OUTPUT
            exit 0
          fi

          runners=$((curl \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.READ_RUNNERS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -sL https://api.github.com/orgs/${{ github.repository_owner }}/actions/runners || echo "") | \
          jq '(.runners // [])[] | select(.status == "online" and .busy == false and .labels[] .name == "self-hosted")'
          if [ -n "$available" ]; then
            echo "runner-label=self-hosted" >> $GITHUB_OUTPUT
          else
            echo "runner-label=ubuntu-latest" >> $GITHUB_OUTPUT
          fi

  cargo-udeps:
    needs: check-runner
    runs-on: ${{ needs.check-runner.outputs.runner-label }}
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v3
        # Main branch is default branch
        # with:
        #   ref: main

      - name: Install rust toolkit
        uses: ./.github/actions/rust

      - name: Install cargo-udeps
        run: cargo install --locked cargo-udeps

      - name: Check for unused dependencies
        run: cargo udeps --workspace --all-targets --all-features

      - name: Create github issue for failed action
        uses: imjohnbo/issue-bot@v3
        if: ${{ failure() }}
        with:
          assignees: "jdkanani, matthiasgoergens"
          labels: "bug, devtools"
          title: "Github action for unused deps check failed"
          body: |
            Failed reference github action job: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            The reference ${{ github.ref_type }} ${{ github.ref }} was at commit ${{ github.sha }} when its run failed.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
