[package]
edition = "2021"
name = "panic"
version = "0.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mozak-sdk = { path = "../../sdk", default-features = false }

[[bin]]
name = "panic"
path = "main.rs"

[features]
std = ["mozak-sdk/std"]
